### ISSUE TITLE
Dark / Light mode (config)

### ISSUE THREAD

**Issue by SergioSuarezDev** [davidwernhart/AlDente#696] opened 2022-06-05 11:41 UTC
**Describe the bug**
Can't see the widget corretly
¿It is possible select the dark or white mode by config?

**To Reproduce**
Enable dark mode only in menubar, not in rest of apps or system
Open the widget in menubar

**Expected behavior**
Good colors

**Screenshots**
<img width="401" alt="Captura de Pantalla 2022-06-05 a las 13 36 41" src="https://user-images.githubusercontent.com/3636232/172048644-c414d8a4-1ab9-4dbc-b301-98fcec644de2.png">

**MacBook (please complete the following information):**
 - MacBook model:  MacBook Pro (15-inch, 2017)
 - AlDente Pro or AlDente Free? Pro
 - AlDente Version? 1.17.1

**Additional context**

**Comment by MatthiasKerbl** [comment] 2022-09-01 13:26
Hi @SergioSuarezDev,

For me, the colors still work flawlessly when I only use dark mode in the menu bar.

<img width="472" alt="Screen Shot 2022-09-01 at 15 24 29" src="https://user-images.githubusercontent.com/33470003/187925165-e0bc58d2-1d72-4552-87f7-097d3b84bd52.png">

Is there any possibility that this is caused by something else?

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment] 2022-10-31 12:29
Hi @SergioSuarezDev,

Do you have any updates on this?
Do you still experience this issue with our newest version Aldente 1.19.1?

Cheers,
Matthias

**Comment by MatthiasKerbl** [comment] 2022-11-06 16:01
Hi @SergioSuarezDev,

Since I did not hear back from you, I will close this issue for now but feel free to give any updates on this.

Cheers,
Matthias

**Closed by MatthiasKerbl** 2022-11-06 16:01 UTC
