### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by wazar** [davidwernhart/AlDente#351] opened 2021-08-13 22:01 UTC
Using Pro (1.06)
Macbook Pro (M1, 2020)
Latest macOS Big Sur

AlDente uses 99.99% CPU in activity monitor and sometimes hangs using 800% (logs attached)
[aldentepro-debug-2021-08-13-18:27:42.pasta.zip](https://github.com/davidwernhart/AlDente/files/6985321/aldentepro-debug-2021-08-13-18.27.42.pasta.zip)
<img width="852" alt="Screenshot 2021-08-14 at 00 01 12" src="https://user-images.githubusercontent.com/16022906/129422367-b48725f4-6c63-4db7-9bf9-a64a51072152.png">

Quitting the app immediately drops CPU temp and load.

**Comment by JongYun-Kim** [comment] 2021-08-15 12:08
I've got the same issue...

100% cpu used.
750-800% cpu is used when I adjust the charge limit...

This makes my MacBook so hot. It's never been this hot before...

I uninstall the free version and installed this pro version on SetApp. 
M1 MBA (11.4 and 11.5.2)

<img width="266" alt="스크린샷 2021-08-15 오후 12 58 32" src="https://user-images.githubusercontent.com/36770713/129477960-83f1a0f8-f3be-4f58-a737-f86b17b45892.png">

**Comment by Rag0n** [comment] 2021-08-16 08:07
Same issue, I'm using AlDente Pro from Setapp and I have MacBook Pro m1.

**Comment by J0n4t4n** [comment] 2021-08-16 09:30
Same, MBA M1 through Setapp.

**Comment by JongYun-Kim** [comment] 2021-08-16 11:27
I heard from AppHouseKitchen that they are working on it. They can't reproduce the bug at the moment though..
And, They added that "The one on SetApp is actually the newest version, which we have not released on GitHub yet. However, we will do so soon."

**Comment by davidwernhart** [comment] 2021-08-18 11:45
Hi Guys!

We are aware of this bug and have finally been able to replicate it.
A fix will be released soon!

Thank you for your patience,

David
AppHouseKitchen

**Comment by JongYun-Kim** [comment] 2021-08-18 12:27
> Hi Guys!
> 
> We are aware of this bug and have finally been able to replicate it.
> A fix will be released soon!
> 
> Thank you for your patience,
> 
> David
> AppHouseKitchen

Thank you very much.

Now that I hear that the new version is released soon, I can't be happier!

**Comment by davidwernhart** [comment] 2021-08-19 13:57
We have just released our new Version 1.07 which fixes this bug. Sorry for the inconveniences and kind regards, David

**Closed by davidwernhart** 2021-08-19 13:57 UTC
