### ISSUE TITLE
Can't get Aldente to install on 11.2.3

### ISSUE THREAD

**Issue by AppleRobert** [davidwernhart/AlDente#173] opened 2021-03-09 23:57 UTC
<img width="611" alt="Screen Shot 2021-03-09 at 6 48 08 PM" src="https://user-images.githubusercontent.com/79120565/110555078-efa21e00-8109-11eb-9c17-018874286129.png">
I just did a fresh install of 11.2.3 and installed AlDente. When I try to open it, I get 2 messages a)  AlDente will damage my computer. You should move it to the trash. b)You don't have permission to open the application AlDente. contact your computer or network admin for assistance. 

I have made sure I am right clicking on the app in the applications folder. I didn't have this problem in prior releases of Big Sur. 

Edited to add: I also tried installing the prior version of AlDente and got the same results.

**Comment by idahorsegirl** [comment] 2021-03-10 02:04
The same thing is happening to me on Big Sur beta 11.3 beta. It started happening after I enabled kernel extensions for an unrelated app.

**Comment by tornupnegatives** [comment] 2021-03-10 04:14
Also experiencing this issue on 11.2.3 (MacBook Pro 2019 15" - Intel)

**Comment by jpirnie** [comment] 2021-03-10 04:14
I was able to get this to work on 11.2.2 - I was getting the same problem.  This fixed it for me.  Try this out and post if it helped you too.  This is what I ran at the terminal:

`codesign --force --deep --sign - /Applications/AlDente.app`

Hope this helps!

**Comment by tornupnegatives** [comment] 2021-03-10 04:18
> I was able to get this to work on 11.2.2 - I was getting the same problem. This fixed it for me. Try this out and post if it helped you too. This is what I ran at the terminal:
> 
> `codesign --force --deep --sign - /Applications/AlDente.app`
> 
> Hope this helps!

This fixed the permissions issue, but it is still not working 100%. AlDente asks for my password at startup each time, but reports that the helper is not found

**Comment by jpirnie** [comment] 2021-03-10 04:23
The codesign command above was needed but not enough by itself.  You also have to right click the app -> Get Info and then check the box called "Override Malware Protection".  Then it will open.

But now the problem is the helper won't install.  When you open the options this is the error:

Helper v10: not found!

Clicking the button to reinstall the helper doesn't help to fix it.

**Comment by jpirnie** [comment] 2021-03-10 04:33
Yeah, it is having trouble installing the helper.  Thats why it is asking for your password - for permissions to attempt the install of the helper which is not working.  So it asks every time.  I'm seeing the same thing.  This is on a 2018 13" MacBook Pro.

**Comment by CoachM** [comment] 2021-03-10 09:34
Same issue here

**Comment by malaltot** [comment] 2021-03-10 09:39
Same

**Comment by teitoku1006** [comment] 2021-03-10 10:17
I'm having the same problem after upgrade to 11.2.3: I shutdown my machine and when I turn on it's no longer work

**Comment by WNDRKND** [comment] 2021-03-10 13:03
Same here. Not working on 11.2.3 M1 MacBook Air.

**Comment by WNDRKND** [comment] 2021-03-10 13:17
> I was able to get this to work on 11.2.2 - I was getting the same problem. This fixed it for me. Try this out and post if it helped you too. This is what I ran at the terminal:
> 
> `codesign --force --deep --sign - /Applications/AlDente.app`
> 
> Hope this helps!

This does not fix the permission problem for me. Terminal gives me this error message:

> codesign --force --deep --sign - /Applications/AlDente.app
> /Applications/AlDente.app: replacing existing signature
> xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): could not use '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' because it is not a compatible arch).
> /Applications/AlDente.app: the codesign_allocate helper tool cannot be found or used
> In subcomponent: /Applications/AlDente.app/Contents/Library/LoginItems/LaunchAtLoginHelper.ap

**Comment by tosbsas** [comment] 2021-03-10 16:22
awfully silent here

**Comment by TheMazus** [comment] 2021-03-10 20:25
Hi Guys,
We are very sorry for the inconvenience with AlDente.
A new fixed version was just released:

"Because of an expired signing certificate, macOS shows a security warning for older versions of AlDente.
This has been fixed with this new (notarized!) update.

For anyone who still has problems (regarding old helper versions that are now marked as a "threat" by MacOS), please try the following steps:

Delete /Library/LaunchDaemons/com.davidwernhart.Helper.plist

Delete /Library/PrivilegedHelperTools/com.davidwernhart.Helper

Restart your MacBook

Install this new version of AlDente as usual"

Best regards,
David & Matthias

**Closed** 2021-03-20 19:53 UTC
